spring:
  datasource:
    #  최초 실행 url - jdbc:h2:~/pushop
    url: jdbc:h2:tcp://localhost/~/pushop
    username: pu
    password:
    driver-class-name: org.h2.Driver
  redis:
    host: localhost
    port: 995

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
#    open-in-view: false


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
